apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ipputcg8i-dotnet-basic
  janus-idp.io/tekton: ipputcg8i-dotnet-basic
  backstage.io/kubernetes-id: ipputcg8i-dotnet-basic
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ipputcg8i-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
